[package]
name = "solana-social-dapp"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "1.9.3"
thiserror = "1.0.24"
borsh = "0.9.1"

[lib]
crate-type = ["cdylib", "lib"]